spring.application.name=PortfolioRiskPlatformDocker

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/portfolio_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:portfolio_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:portfolio_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=false

spring.batch.job.enabled=false

app.scheduling.enabled=${APP_SCHEDULING_ENABLED:true}